org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8

# Crucial configuration parameters for extension compiler stability
android.useAndroidX=true
android.enableJetifier=false
android.defaults.buildfeatures.buildconfig=true

org.gradle.caching=true
org.gradle.configuration-cache=false

# Suppress compilation target warning behaviors
android.javaCompile.suppressSourceTargetDeprecationWarning=true
android.suppressUnsupportedCompileSdk=36
